-- This file was generated with UnveilR V3.01 at discord.gg/threaded using the testing version.

local fenv = getfenv();
local success = pcall(function(p1, p2, p3, p4, a, b, c)
    getgenv()["khen was here"] = function(p1_0, p2_0, p3_0, p4_0, p5_0, p6_0, a_0, b_0, c_0) end;
    local v0 = fenv.ycSre8AVug2kIb;
end);
local v1 = type(debug);
local v3, Pcall_Result = pcall(debug.getinfo, pcall);
local v5 = not Pcall_Result;
local v6 = Pcall_Result.what;
local v7 = Pcall_Result.source;
local v8 = Pcall_Result.source;
local v9 = fenv.omdqUsb59uuou;
local v11, Pcall_Result_2 = pcall(debug.getinfo, xpcall);
local v13 = not Pcall_Result_2;
local v14 = Pcall_Result_2.what;
local v15 = Pcall_Result_2.source;
local v16 = Pcall_Result_2.source;
local v18, Pcall_Result_3 = pcall(debug.getinfo, assert);
local v20 = not Pcall_Result_3;
local v21 = Pcall_Result_3.what;
local v22 = Pcall_Result_3.source;
local v23 = Pcall_Result_3.source;
local v26, Pcall_Result_4 = pcall(debug.getinfo, tostring);
local v28 = not Pcall_Result_4;
local v29 = Pcall_Result_4.what;
local v30 = Pcall_Result_4.source;
local v31 = Pcall_Result_4.source;
local v34, Pcall_Result_5 = pcall(debug.getinfo, type);
local v36 = not Pcall_Result_5;
local v37 = Pcall_Result_5.what;
local v38 = Pcall_Result_5.source;
local v39 = Pcall_Result_5.source;
local v41, Pcall_Result_6 = pcall(debug.getinfo, getmetatable);
local v43 = not Pcall_Result_6;
local v44 = Pcall_Result_6.what;
local v45 = Pcall_Result_6.source;
local v46 = Pcall_Result_6.source;
local v48, Pcall_Result_7 = pcall(debug.getinfo, setmetatable);
local v50 = not Pcall_Result_7;
local v51 = Pcall_Result_7.what;
local v52 = Pcall_Result_7.source;
local v53 = Pcall_Result_7.source;
local v55, Pcall_Result_8 = pcall(debug.getinfo, rawget);
local v57 = not Pcall_Result_8;
local v58 = Pcall_Result_8.what;
local v59 = Pcall_Result_8.source;
local v60 = Pcall_Result_8.source;
local v62, Pcall_Result_9 = pcall(debug.getinfo, rawset);
local v64 = not Pcall_Result_9;
local v65 = Pcall_Result_9.what;
local v66 = Pcall_Result_9.source;
local v67 = Pcall_Result_9.source;
local v69, Pcall_Result_10 = pcall(debug.getinfo, next);
local v71 = not Pcall_Result_10;
local v72 = Pcall_Result_10.what;
local v73 = Pcall_Result_10.source;
local v74 = Pcall_Result_10.source;
local v76, Pcall_Result_11 = pcall(debug.getinfo, pairs);
local v78 = not Pcall_Result_11;
local v79 = Pcall_Result_11.what;
local v80 = Pcall_Result_11.source;
local v81 = Pcall_Result_11.source;
local v82 = getmetatable(_G);
local v83 = math.random(1e5, 999999);
local success_1 = pcall(function(p1_13, p2_13, a_13, b_13, c_13)
    local v84 = fenv["5y1eXoUWuvkamy"];
end);
local success_2, v86 = pcall(function(p1_14, p2_14, a_14, b_14, c_14)
    local v85 = fenv.K4avW1SkYhdjwh;
    return 1 / 0;
end);
local v87 = math.random(5, 95);
local success_3, v89 = pcall(function(p1_15, a_15, b_15, c_15)
    local v88 = fenv["3bHlJg0BLYeOw"];
    return -0.02040816326530612;
end);
error"attempt to index nil with 'gsub'"; 
